### ISSUE TITLE
herokuの新料金プランへの対応

### ISSUE THREAD

**Issue by machu** [tdiary/rpaproxy-sinatra#35]
Herokuが新料金プランに移行したため、7月15日以降はfreeプランが適用され、1日6時間スリープ状態となります。

https://blog.heroku.com/archives/2015/6/15/dynos-pricing-ga

> We will begin migrating free applications to the free dynos after July 15th, 2015.

$7/mon払うほどのサービスでもないと思うので、僕のVPSサーバに移行するのはどうでしょう。以下のアドレスで試運転しています。現行サイトからデータ移行済みです。
http://rpaproxy.machu.jp/

ポータビリティを確保するため、Docker上で動かしています。
https://github.com/machu/machu-jp/blob/master/rpaproxy/docker-compose.yml

rpaproxy.tdiary.orgのDNS向き先を変えてもらえれば、そのまま動くようにしています。

**Comment by tdtds** [comment]
どれどれ、と見に行ったら503が出てましたw 安定稼働してるようなら切り替えちゃうんですが、どんな感じでしょう?

**Comment by machu** [comment]
サービスが落ちていたので再起動しました。同一dockerデーモン上で動かしているtdiaryとpukiwikiは安定稼働しているので、もう少し様子みてみますか。

**Comment by tdtds** [comment]
そうしましょう

**Comment by tdtds** [comment]
さて、そろそろ行きますぜ。

**Comment by machu** [comment]
了解です！
ここ1週間は安定して動いてます。

**Comment by tdtds** [comment]
CNAMEにrpaproxy.machu.jpを指定する形でDNSを切り替えました。TTL長めのままなので、のんびり切り替わると思います。

**Comment by machu** [comment]
ログ見ると、ちゃんと新しいサイトにもアクセスがきていました。tDiaryのAmazonプラグインも問題なく動いていますね。

**Comment by hsbt** [comment]
対応お疲れ様です!

**Comment by tdtds** [comment]
旧サーバにはもうアクセスないですね。これはほっといてもFreeプランに落ちるのかな。このissueはcloseします。
