### ISSUE TITLE
Product Advertising API 利用ポリシーの変更

### ISSUE THREAD

**Issue by tdtds** [tdiary/rpaproxy-sinatra#42]
アソシエイト会員にはメールが来ていると思いますが、[Product Advertising API 利用ポリシーの変更](https://affiliate.amazon.co.jp/help/topic/t52/)という通達が出ています。具体的には:

* 初期リクエスト可能数 : 1日あたり 8,640リクエスト（API利用開始より60日間）
* PA-APIより取得した商品リンクより発生した、過去30日間の発送済み商品売上$0.05（日本円で約5円）ごとに1リクエスト追加
* 1日の最大リクエスト可能数は、1日あたり864,000リクエスト

ということで、認証プロキシを運用している人のアカウントで売上がないとそもそも継続して運用ができなくなりそうです。つまり、rpaproxyを事実上のオープンプロキシとして運用することに無理が出てくると思われます。

しかも(例によって)この新運用開始まで半月しか猶予がありません。早急に方針を決める必要があります。ここを見ている人がどれくらいいるのか不明なんですが、ご意見があればコメントいただきたく。

**Comment by kurumigi** [comment]
認証プロキシ提供者の末席を汚しております∵ごま∴と申します。
念の為、Amazon側のポリシー変更に伴いAssociateTagの書き換えを行うようになった旨を、rpaproxyのトップページに明記しておいたほうが良いかと思います。
過去に「無断でAssociateTagを書き換えた」として炎上した事例もありますので……。

**Comment by hsbt** [comment]
ポリシー変更に伴う処置としての注意書きを書いたうえで運営者の AssociateTag で上書きするに賛成ですー。

**Comment by tdtds** [comment]
そのような注意書きを加えるPRを作った #43 
@machu 取り込んだ上でサーバをアップデートしてもらえますか?

**Comment by machu** [comment]
反応できてなくてすみません。PR取り込み了解です。
