### ISSUE TITLE
大量アクセスbotを自動でブラックリストに入れる

### ISSUE THREAD

**Issue by machu** [tdiary/rpaproxy-sinatra#9]
1〜2回/秒の頻度でアクセスするお行儀の悪いクライアントへの対策。
今は `IGNORE_ASSOCIATE_TAGS` にNGリストを登録しているが、これを自動的にブラックリストに入れ、アクセス拒否したい。

**Comment by machu** [comment]
PR送りました。レビューお願いします！ > @tdtds

**Comment by tdtds** [comment]
ぎょえー、先に実装されてしまったw
(できれば)今日中にみます。しばしお待ちを。

**Comment by tdtds** [comment]
PR #23 で解決。closeします。

**Comment by tdtds** [comment]
Deployしました。
